# All bosses attacks, spawn broadcast and runnable commands on death is configured here

bossConfig:
  spawnBroadcast:
    - "&a&lThe {bossName} BOSS has spawned!"
    - "&eGo to X: {x} Y: {y} Z: {z} World: {world} to kill the {bossName}!"
    - "&eAnd won the rewards!"
    - "&6Boss info:"
    - "&d Type: {bossType}"
    - "&d Damage: {bossDamage}"
    - "&d Scale: {bossScale}"
    - "&d Speed: {bossSpeed}"
    - "&d Life: {bossLife}"
  deathCommands:
    - say {last_damager} has killed the boss!
  attacks:
    negativeEffects:
      cooldown: 20
      duration: 10
      radius: 8
    explosion:
      cooldown: 10
      radius: 8
    minions:
      cooldown: 10
      spawnAmount: 3
      maxHealth: 20
